# Copyright Â© 2023 OpenIM open source community. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

app:
  version: 1.0-dev
  debug: true
  log_file: logs/

server:
  ip: 127.0.0.1
  port: 10010

jwt:
  secret: openkf
  issuer: openkf
  expire_days: 1

mysql:
  ip: 127.0.0.1
  port: 3307
  username: root
  password: 123123
  database: openkf
  max_lifetime: 120
  max_open_conns: 100
  max_idle_conns: 20

redis:
  ip: 127.0.0.1
  port: 6380
  password: openkf
  database: 0

minio:
  ip: 127.0.0.1
  port: 9123
  access_key_id: test123123
  secret_access_key: test123123
  bucket: openkf
  app_bucket: openkf
  location: us-east-1

email:
  host: # smtp address
  port: 25
  from: # email address
  nickname: openkf
  password: # smtp password

openim:
  secret: openkf
  ip: 127.0.0.1
  api_port: 10002
