# Copyright Â© 2023 OpenIM open source community. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: "3"

networks:
  openkf-network:
    ipam:
      driver: default
      config:
        - subnet: '177.8.0.0/16'
        
services:
  mysql:
    image: mysql:5.7
    container_name: openkf-mysql
    hostname: openkf-mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    ports:
      - "3406:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123123
      - MYSQL_DATABASE=openkf
      # - MYSQL_USER=root
      # - MYSQL_PASSWORD=123123
      # - MYSQL_MAX_LIFETIME=120
      # - MYSQL_MAX_OPEN_CONNS=100
      # - MYSQL_MAX_IDLE_CONNS=20
    volumes:
      - mysql_data_573:/var/lib/mysql
    networks:
      openkf-network:
        ipv4_address: 177.8.0.3

  redis:
    image: redis:latest
    container_name: openkf-redis
    hostname: openkf-redis
    command: redis-server --requirepass openkf
    restart: always
    ports:
      - '6479:6379'
    volumes:
      - redis_data:/data
    networks:
      openkf-network:
        ipv4_address: 177.8.0.4

  minio:
    image: minio/minio
    container_name: openkf-minio
    ports:
      - "9100:9000"
      - "9190:9090"
    volumes:
      - minio_data:/data
      - minio_config:/root/.minio
    environment:
      - MINIO_ROOT_USER=test123123
      - MINIO_ROOT_PASSWORD=test123123
      - MINIO_BUCKET=openkf
      - MINIO_SERVER_URL=http://127.0.0.1:9000
    command: minio server /data --console-address ':9090'
    networks:
      openkf-network:
        ipv4_address: 177.8.0.5
  
  influxdb:
    image: influxdb:2.7.1
    container_name: openkf-influxdb
    ports:
      - "8186:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin1234
      - DOCKER_INFLUXDB_INIT_ORG=openkf
      - DOCKER_INFLUXDB_INIT_BUCKET=openkf
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=admin1234
    networks:
      openkf-network:
        ipv4_address: 177.8.0.6

  # For milvus db
  milvus-etcd:
    container_name: openkf-milvus-etcd
    image: quay.io/coreos/etcd:v3.5.0
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - milvus-etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    networks:
      openkf-network:
        ipv4_address: 177.8.0.7

  milvus-minio:
    container_name: openkf-milvus-minio
    image: minio/minio:RELEASE.2022-03-17T06-34-49Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - milvus-minio:/minio_data
    command: minio server /minio_data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      openkf-network:
        ipv4_address: 177.8.0.8

  milvus-standalone:
    container_name: openkf-milvus-standalone
    image: milvusdb/milvus:v2.1.4
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: milvus-etcd:2379
      MINIO_ADDRESS: milvus-minio:9000
    volumes:
      - milvus-standalone:/var/lib/milvus
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - "milvus-etcd"
      - "milvus-minio"
    networks:
      openkf-network:
        ipv4_address: 177.8.0.9

volumes:
  openkf_logs:
  mysql_data_573:
  redis_data:
  minio_data:
  minio_config:
  influxdb_data:
  milvus-etcd:
  milvus-minio:
  milvus-standalone: